# Generated by go2rpm
%bcond_without check

# https://github.com/linuxdeepin/go-x11-client
%global goipath         github.com/linuxdeepin/go-x11-client
Version:                0.6.1
%global tag             %{version}

%gometa

%global goname          golang-github-linuxdeepin-go-x11-client
%global godevelname     golang-github-linuxdeepin-go-x11-client-devel

%global common_description %{expand:
A X11 client Go bindings for Deepin Desktop Environment.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README debian/changelog

Name:           %{goname}
Release:        1%{?dist}
Summary:        X11 client Go bindings for Deepin Desktop Environment

License:        GPLv3
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/text/encoding/charmap)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(gopkg.in/check.v1)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
rm -rf tools/gen

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
